version: '3.8'

services:
  vault:
    image: hashicorp/vault:1.15
    container_name: vault
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
    command: server -dev
    cap_add:
      - IPC_LOCK
    networks:
      - vaultnet

  web:
    build: ./app
    container_name: vault_web
    ports:
      - "5000:5000"
    environment:
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=root
    depends_on:
      - vault
    networks:
      - vaultnet

networks:
  vaultnet:
