version: '3.8'

services:
  jenkins:
    build: ./jenkins
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/workspace
    networks:
      - vaultnet

  vault:
    image: hashicorp/vault:1.15
    container_name: vault
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
    command: server -dev
    cap_add:
      - IPC_LOCK
    networks:
      - vaultnet

  web:
    build: ./app
    container_name: vault_web
    ports:
      - "5000:5000"
    environment:
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=root
    networks:
      - vaultnet

volumes:
  jenkins_home:

networks:
  vaultnet:
